[profile.default]
src = './'
test = './'
out = 'forge-out'
cache_path = 'forge-cache'
libs = []
solc_version = "0.8.19"
gas_reports = ["*"]
optimizer = true
optimizer_runs = 99999
ffi=true
allow_paths = ['/'] # See https://github.com/aspect-build/rules_sol/blob/df20faf05464254a1d2ab2a5e1dace335900bbc5/sol/private/sol_binary.bzl#L113

# See more config options https://github.com/foundry-rs/foundry/tree/master/config